service: hello-laravel-bref

provider:
    name: aws
    region: us-west-2
    runtime: provided
    environment:
        # Laravel environment variables
        APP_STORAGE: '/tmp'

plugins:
    - ./vendor/bref/bref

functions:
    website:
        handler: public/index.php
        timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
    # artisan:
    #     handler: artisan
    #     timeout: 120 # in seconds
    #     layers:
    #         - ${bref:layer.php-73} # PHP
    #         - ${bref:layer.console} # The "console" layer
